"SingleScaleRetinex":
    Node:
        Name: "SingleScaleRetinex"
        ColorSpace: "bgr8"
        In:
            Topic: "/bluefox_camera/image_raw"
            Compressed: "No"
        Out:
             Topic: "/RRetinex/SingleScale"
             Compressed: "No"
             Format: "jpeg"
    Retinex:
        Variance: 150
    Alias: "SSR"

"MultiScaleRetinex":
    Node:
        Name: "MultiScaleRetinex"
        ColorSpace: "bgr8"
        In:
            Topic: "/bluefox_camera/image_raw/"
            Compressed: "No"
        Out:
             Topic: "/RRetinex/MultiScaleRetinex"
             Compressed: "No"
             Format: "jpeg"
    Retinex:
        Variance: [200, 20, 30]
    Alias: "MSR"