Node:
    Name: "enhancer_scheduler"
    Topics:
        camera_out: "/camera/fisheye1/image_raw"
        enhancing_in: "img_req_enhancer"
        enhancing_out: "/img_enhanced"

Image:
    format: "rgb8"

Scheduler:
    time_msec: 1000

Debugging: "yes"
