"SingleScaleRetinex":
    Node:
        Name: "SingleScaleRetinex"
        ColorSpace: "bgr8"
        In:
            Topic: "/bluefox_camera/image_raw"
            Compressed: "No"
        Out:
             Topic: "/RRetinex/SingleScale"
             Compressed: "No"
             Format: "jpeg"
    Retinex:
        Variance: 100

"MultiScaleRetinex":
    Node:
        Name: "MultiScaleRetinex"
        ImgFormat: "gbr8"
        In:
            Topic: "/bluefox_camera/image_raw/compressed"
            Compressed: "Yes"
        Out:
             Topic: "/RRetinex/MultiScaleRetinex"
             Compressed: "No"
             Format: "jpeg"
    Retinex:
        Variance: [15, 80, 30]